os: linux
language: python
python: "3.7"
dist: bionic 
compiler:
  - gcc
before_install:
  - sudo apt-get -y install ninja
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
script:
# Download dependencies and build project
  - rm -rf build
  - mkdir build
  - cd build
  - conan install .. -s compiler.version='9' -s compiler.libcxx='libstdc++11' -s compiler.cppstd='20'
  - conan build ..
