linux: &linux
  os: linux
  dist: xenial
  language: python
  python: "3.7"
  services:
    - docker

osx: &osx
  os: osx
  osx_image: xcode11.3
  env: CXX=clang++
  language: python
  python: "3.7"
  services:
    - docker

matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 VARIANT=coverage
    - <<: *osx
      env: CONAN_CLANG_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/clang9

before_install:
  - pip install conan

install:
  - pip install -U conan_package_tools
  - conan user

script:
  - python .travis_build.py