linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
  osx_image: xcode11.3
  env: CXX=clang++ VARIANT=valgrind
matrix:
   include:
     - <<: *linux
       env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9

before_install:
  - pip install codecov

install:
  - pip install -U conan_package_tools
  - conan user

script:
  - python .travis_build.py
  - codecov -t cb7ee84a-0116-4adb-9892-afa9a3db49bf

after_success: 
  - bash <(curl -s https://codecov.io/bash)