version: '{build}'

platform: x64

image: Visual Studio 2019

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: pip.exe install conan_package_tools
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan --profile --detect

build_script:
  - cmd: mkdir build && cd build
  - cmd: conan install .. -b missing
  - cmd: conan build ..

test_script:
  - cmd: cd build
  - cmd: ctest